/**:
    ros__parameters:
        image_transport: raw    # image format
        family: 36h11           # tag family name
        size: 0.173             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 1          # number of threads
            decimate: 2.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: True        # snap to strong gradients
            sharpening: 0.25    # sharpening of decoded images
            debug: False        # write additional debugging images to current working directory

        # optional list of tags
        tag:
            ids: [5, 2, 3, 0]   # tag ID in order top left, top right, bottom left, bottom right.
            frames: [satellite_tag_2901, satellite_tag_2902, satellite_tag_2903, satellite_tag_2904]  # optional frame name
            sizes: [0.051, 0.051, 0.051, 0.051]   # optional tag-specific edge size
