###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

# Extend the basic Kinova MuJoCo configuration
based_on_package: kinova_gen3_mujoco_config

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "picknik_kinova_satellite_sim"
      path: "description/picknik_kinova_satellite_sim.xacro"
    srdf:
      package: "picknik_kinova_satellite_sim"
      path: "config/moveit/picknik_kinova_satellite_sim.srdf"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - arm: "gen3"
      - dof: "7"
      - mujoco_keyframe: "moving_satellite"
      - mujoco_model: "description/mujoco/scene.xml"
      - mujoco_viewer: "true"

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "force_torque_sensor_broadcaster"
    - "robotiq_gripper_controller"
    - "joint_state_broadcaster"
    - "servo_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  controllers_inactive_at_startup:
    - "joint_trajectory_controller"
    - "joint_trajectory_admittance_controller"
    - "velocity_force_controller"

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core:
      package_name: "picknik_kinova_satellite_sim"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "picknik_kinova_satellite_sim"
    relative_path: "waypoints/waypoints.yaml"
