###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

# Extend the Kinova satellite sim configuration
based_on_package: "picknik_kinova_satellite_sim"

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "picknik_006_gen3_hw"
      path: "description/picknik_006_gen3_hw.xacro"
    srdf:
      package: "picknik_006_gen3_hw"
      path: "config/moveit/picknik_006_gen3_hw.srdf"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - arm: "gen3"
      - dof: "7"
      - vision: "true"
      - robot_ip:  "192.168.1.10"
      - gripper: "robotiq_2f_85"
      - username: "admin"
      - password: "admin"
      - port: "10000"
      - port_realtime: "10001"
      - session_inactivity_timeout_ms: "60000"
      - connection_inactivity_timeout_ms: "2000"
      - use_fake_hardware: "false"
      - fake_sensor_commands: "false"
      - use_internal_bus_gripper_comm: "false"
      # When set to true, use_external_cable enforces joint limits on
      # continuous joints to avoid cable wrapping
      - use_external_cable: "false"
      - gripper_com_port: "/dev/ttyUSB0"


# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "force_torque_sensor_broadcaster"
    - "robotiq_gripper_controller"
    - "joint_state_broadcaster"
    - "servo_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  controllers_inactive_at_startup:
    - "joint_trajectory_controller"
    - "joint_trajectory_admittance_controller"
    - "velocity_force_controller"

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    gen3_hw_objectives:
      package_name: "picknik_006_gen3_hw"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "picknik_006_gen3_hw"
    relative_path: "waypoints/waypoints.yaml"
