robot_calibration:
  ros__parameters:
    chains:
    - arm
    arm:
      topic: /joint_trajectory_controller/follow_joint_trajectory
      joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      #planning_group: arm TODO: revert when moveit is setup
    features:
    - checkerboard_finder
    checkerboard_finder:
      type: robot_calibration::CheckerboardFinder2d
      topic: /zed2i_camera/left/image_raw_color
      camera_info_topic: /zed2i_camera/left/camera_info
      camera_sensor_name: camera
      camera_link: scene_camera_mount_link
      chain_sensor_name: arm
      frame_id: checkerboard # Name of checkerboard frame (if not specified it defaults to: checkerboard)
      debug: true
      # Number of inner corners per a chessboard row and column
      points_x: 5
      points_y: 4
      size: 0.025
